// <auto-generated />
namespace BA.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedDbEntites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedDbEntites));
        
        string IMigrationMetadata.Id
        {
            get { return "201705312117513_changedDbEntites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
