// <auto-generated />
namespace BA.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatingblogtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatingblogtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201706181928272_updatingblogtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
